
spring:
  application:
    name: booking-microservice
  cloud:
    config:
      username: root
      password: s3cr3t
  config:
    import: optional:configserver:http://localhost:8099,optional:file:./booking-microservice/.env[.properties],optional:file:./.env[.properties]


server:
  port: 8084

