spring:
  application:
    name: api-gateway

  cloud:
    config:
      username: root
      password: s3cr3t
      charset:

  config:
    import: configserver:http://localhost:8099,optional:file:./api-gateway/.env[.properties],optional:file:./.env[.properties]


