server:
  port: 8084
  
spring:
  application:
    name: booking-microservice
  h2:
    console:
      enabled: true

    datasource:
      url: jdbc:h2:mem:driverDB;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: tony
      password:

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: false
          format_sql: false

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
