server:
  port: 8023

spring:
  application:
    name: driver-microservice
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:driverDB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: tony
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  boot:
    admin:
      client:
        url: http://localhost:8444
        instance:
          service-host-type: ip


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  public-key: ${JWT_PUBLIC_KEY}



resilience4j:
  circuitbreaker:
    instances:
      user-microservice:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 5
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      user-microservice:
        max-attempts: 4
        wait-duration:
          seconds: 10