
spring.application.name=user-microservice
spring.config.import=optional:configserver:http://localhost:8099,optional:file:./user-microservice/.env[.properties],optional:file:./.env[.properties]
spring.cloud.config.username=root
spring.cloud.config.password=s3cr3t

