CREATE TABLE IF NOT EXISTS permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_permission
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name              VARCHAR(255),
    email                  VARCHAR(255),
    age                    INTEGER                                 NOT NULL,
    password               TEXT,
    register_at            TIMESTAMP WITHOUT TIME ZONE,
    is_enabled             BOOLEAN,
    account_no_locked      BOOLEAN,
    credentials_no_expired BOOLEAN,
    role_id                BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "value" TEXT,
    "type"  VARCHAR(255),
    revoked BOOLEAN,
    expired BOOLEAN,
    user_id BIGINT,
    CONSTRAINT pk_token PRIMARY KEY(id)


);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE role_permission
    ADD CONSTRAINT fk_rolper_on_permissions FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permission
    ADD CONSTRAINT fk_rolper_on_roles FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE token ADD CONSTRAINT fk_users_on_token FOREIGN KEY (user_id) REFERENCES users (id);