
spring:
  application:
    name: booking-microservice
  cloud:
    config:
      username: root
      password: s3cr3t
  config:
    import: configserver:http://localhost:8099

server:
  port: 8084

