spring:
  application:
    name: config_server

  config:
    import: optional:file:./config_server/.env[.properties],optional:file:./.env[.properties]

  profiles:
    active: ${ACTIVE_PROFILE}

server:
  port: 8099