spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tonysalinas-futdev/spring-microservices-practice.git
          search-paths: config-data


  security:
    user:
      name: root
      password: s3cr3t
  config:
    import: optional:file:.../../.env[.properties],optional:file:./.env[.properties]

server:
  port: 8099