spring:

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/Tony/Desktop/spring-microservices/config_data


  security:
    user:
      name: root
      password: s3cr3t
